#include <unity.h>
#include <cstring>
#include "logic/firmware_manifest.h"

void setUp() {}
void tearDown() {}

static const char *GOOD =
    "# generated by ci.yml\n"
    "build=1284\n"
    "hash=a1b2c3d4\n"
    "md5_ee02=0123456789abcdef0123456789abcdef\n"
    "md5_ee03=ffffffffffffffffffffffffffffffff\n";

void test_valid_parse() {
    ManifestInfo m;
    TEST_ASSERT_TRUE(parseManifest(GOOD, "ee02", m));
    TEST_ASSERT_EQUAL_UINT32(1284, m.build);
    TEST_ASSERT_EQUAL_STRING("a1b2c3d4", m.hash);
    TEST_ASSERT_EQUAL_STRING("0123456789abcdef0123456789abcdef", m.md5);
}

void test_picks_correct_board() {
    ManifestInfo m;
    TEST_ASSERT_TRUE(parseManifest(GOOD, "ee03", m));
    TEST_ASSERT_EQUAL_STRING("ffffffffffffffffffffffffffffffff", m.md5);
}

void test_crlf_and_surrounding_spaces() {
    const char *body =
        "  build = 7 \r\n"
        "\tmd5_ee04 =  ABCDEF0123456789ABCDEF0123456789  \r\n";
    ManifestInfo m;
    TEST_ASSERT_TRUE(parseManifest(body, "ee04", m));
    TEST_ASSERT_EQUAL_UINT32(7, m.build);
    // md5 normalized to lower-case
    TEST_ASSERT_EQUAL_STRING("abcdef0123456789abcdef0123456789", m.md5);
}

void test_missing_build_fails() {
    const char *body = "md5_ee02=0123456789abcdef0123456789abcdef\n";
    ManifestInfo m;
    TEST_ASSERT_FALSE(parseManifest(body, "ee02", m));
}

void test_zero_or_nonnumeric_build_fails() {
    ManifestInfo m;
    TEST_ASSERT_FALSE(parseManifest(
        "build=0\nmd5_ee02=0123456789abcdef0123456789abcdef\n", "ee02", m));
    TEST_ASSERT_FALSE(parseManifest(
        "build=x9\nmd5_ee02=0123456789abcdef0123456789abcdef\n", "ee02", m));
}

void test_board_absent_fails() {
    ManifestInfo m;
    TEST_ASSERT_FALSE(parseManifest(GOOD, "ee05", m));
}

void test_bad_md5_length_or_charset_fails() {
    ManifestInfo m;
    TEST_ASSERT_FALSE(parseManifest("build=1\nmd5_ee02=deadbeef\n", "ee02", m));
    TEST_ASSERT_FALSE(parseManifest(
        "build=1\nmd5_ee02=zzzz456789abcdef0123456789abcdef\n", "ee02", m));
}

void test_prefix_key_not_confused() {
    // "md5_ee02" must not match a line "md5_ee020=..."
    const char *body = "build=1\nmd5_ee020=0123456789abcdef0123456789abcdef\n";
    ManifestInfo m;
    TEST_ASSERT_FALSE(parseManifest(body, "ee02", m));
}

int main() {
    UNITY_BEGIN();
    RUN_TEST(test_valid_parse);
    RUN_TEST(test_picks_correct_board);
    RUN_TEST(test_crlf_and_surrounding_spaces);
    RUN_TEST(test_missing_build_fails);
    RUN_TEST(test_zero_or_nonnumeric_build_fails);
    RUN_TEST(test_board_absent_fails);
    RUN_TEST(test_bad_md5_length_or_charset_fails);
    RUN_TEST(test_prefix_key_not_confused);
    return UNITY_END();
}
